### ISSUE TITLE
Add symfony server as dev requirement

### ISSUE THREAD

**Issue by flackovic** [NullTraining/project-team1#66]
Add symfony server as dev requirement in order to serve webapp while developing

**Comment by HcsOmot** [comment]
Why would we need to use symfony server for dev? We're using vagrant. Or am I missing something? 😕

**Comment by flackovic** [comment]
I switched from vagrant because of various problems

**Comment by HcsOmot** [comment]
ok, but did 4ccc612e9ca6c3f2 fix the problems you were having?

**Comment by flackovic** [comment]
@HcsOmot unfortunately no. Closing this PR because of conflicts, ill open new one
